"""Create profile table

Revision ID: 419fb30047e1
Revises: 8396acbad56c
Create Date: 2024-01-02 15:38:43.565627

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '419fb30047e1'
down_revision: Union[str, None] = '8396acbad56c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
                    sa.Column('first_name', sa.String(length=40), nullable=True),
                    sa.Column('last_name', sa.String(length=40), nullable=True),
                    sa.Column('bio', sa.String(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    # ### end Alembic commands ###
